version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbauth
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
  adminer:
    image: adminer:4
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080
  app:
      container_name: auth-api
      restart: always
      build: .
      ports:
        - "3333:3333"
      depends_on:
       - db